// Static blog data — flat structure for fast SSR + clean SEO.
// Each post is keyed by slug; content uses a tiny block format the renderer understands.

export const BLOG_POSTS = [
  {
    slug: 'choosing-the-perfect-wedding-website-template',
    title: 'How to Choose the Perfect Wedding Website Template for Your Big Day',
    eyebrow: 'The choice that sets the tone',
    excerpt:
      'A template is the first promise of your wedding. Here is the gentle, considered way to pick one that feels like you — across mood, ceremony, palette and the small details that linger.',
    cover: 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?w=1400&q=80',
    author: 'The Vivoha Studio',
    date: '2026-02-18',
    readTime: '8 min read',
    tags: ['Templates', 'Planning'],
    seoTitle: 'How to Choose the Perfect Wedding Website Template · Vivoha',
    seoDescription:
      'A studio guide to choosing a wedding website template — match the mood, ceremony, palette, and culture to a design that feels unmistakably you.',
    body: [
      { type: 'p', text: 'A wedding website is the very first invitation. Before guests see your flowers, taste your food or hear the band, they meet you — through a screen. Which is why the template you choose carries far more weight than it seems to. It sets the emotional tone, signals the formality, and gently tells your guests how to feel.' },
      { type: 'p', text: 'After designing thousands of wedding pages across India and beyond, the Vivoha studio has reduced this decision into five quiet questions. Sit with them. Reread your favourite parts. The right template will reveal itself.' },
      { type: 'h2', text: '1. What is the single feeling you want your guests to have?' },
      { type: 'p', text: 'Not the colours. Not the dress code. The feeling. Open. Awe-struck. Cosy. Cinematic. Sacred. Playful. When a couple says, "I want it to feel like a long, quiet morning in our grandmother\'s house," we know almost exactly which template to build them. When another says, "I want our friends to feel like they are stepping into a film," that points to an entirely different design language.' },
      { type: 'p', text: 'Try this: write the feeling down in three words on a piece of paper. If those words feel close to "minimal · editorial · timeless", explore Moonveil. If they feel like "regal · burgundy · ancient", lean towards Royal Heritage or Sapphire Saga. If "garden · soft · floral" comes up, Crimson Lotus or Albion Vow will sing. The mood, named honestly, is the compass.' },
      { type: 'h2', text: '2. Which ceremony are you honouring?' },
      { type: 'p', text: 'The right template should hold your tradition without making it feel decorative. A Tamil-Brahmin wedding needs kalashams, kolam and gopurams — Banyan & Brass weaves them in with quiet reverence. A Muslim nikah is held with Bismillah calligraphy, eight-pointed stars and arabesque vines — Jannah Vow understands that vocabulary. A Christian service finds its hush in Sanctum Veil\'s cathedral arches. Letting your template speak the language of your ceremony is not a small kindness — it is one of the deepest ones.' },
      { type: 'h2', text: '3. Where is the palette already living in your story?' },
      { type: 'p', text: 'Look around. The dupatta your mother stitched. The colour of your engagement ring. The flowers you keep saving on Pinterest. There is almost always a quiet palette already at work — long before you started planning. Pull two anchor colours from it. They will tell you whether you belong in a deep emerald + gold (Pearl & Velvet), a midnight + silver (Sapphire Saga), a marigold + emerald (Marigold Bloom), or an ivory + slate (Moonveil).' },
      { type: 'p', text: 'A short trick: hold the two colours next to each other on your phone. If they make your shoulders soften, you have your palette. If they fight, keep looking.' },
      { type: 'h2', text: '4. How many events are you welcoming guests to?' },
      { type: 'p', text: 'Some weddings are one ceremony, held with a single, perfect breath. Others span four days — mehendi, sangeet, ceremony, reception — each with its own dress code, mood and venue. Templates like Royal Heritage and Eternal Edit make space for multi-event journeys; Moonveil and Sanctum Veil suit a single, ceremonious day. Choose a template that has room for your story without straining to fill it.' },
      { type: 'h2', text: '5. What will your favourite photos look like, framed inside the design?' },
      { type: 'p', text: 'Open the live demos. Replace the placeholder image, in your mind, with your own photograph — the engagement shoot, the candid moment, the temple steps. If your photos look at home, you have found it. If they feel jarring, gently keep going. A template is, in the end, a frame for your faces.' },
      { type: 'h2', text: 'A note on the "perfect" template' },
      { type: 'p', text: 'There is no such thing. There is only the template that feels like you on a Tuesday at noon, on a Saturday at midnight, on the morning of your wedding. Pick the one that whispers, not the one that shouts.' },
      { type: 'p', text: 'And remember — the entire Vivoha collection is hand-crafted by our studio team. Whichever template you choose, we tune the palette, the photography, the spacing and the words until it is not just a beautiful website, but unmistakably yours.' },
      { type: 'cta', text: 'Begin with a free design consultation', href: '/#pricing' },
    ],
  },
  {
    slug: 'indian-wedding-traditions-online',
    title: '10 Indian Wedding Traditions You Can Beautifully Showcase Online',
    eyebrow: 'Heritage, reframed gently for the modern guest',
    excerpt:
      'A wedding website is a stage on which to introduce your traditions — to family abroad, to friends from other cultures, to the future you. Here are ten quiet ways to let your heritage shine on the page.',
    cover: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?w=1400&q=80',
    author: 'The Vivoha Studio',
    date: '2026-02-15',
    readTime: '11 min read',
    tags: ['Tradition', 'Culture'],
    seoTitle: '10 Indian Wedding Traditions to Beautifully Showcase Online · Vivoha',
    seoDescription:
      'A studio guide to introducing your Indian wedding traditions — mehendi, haldi, sangeet, baraat and more — through a thoughtful, modern wedding website.',
    body: [
      { type: 'p', text: 'There is a particular tenderness to explaining your wedding to those who will not always know its rituals. The cousin abroad. The friend from a different faith. The child you will tell about all of this, twenty years from now. A wedding website becomes a soft, hospitable bridge — it lets you welcome guests into your tradition without lecturing them, while also recording the day for yourselves.' },
      { type: 'p', text: 'Below are ten Indian rituals our studio loves to showcase, and the smallest design moves that let each one breathe on the page.' },
      { type: 'h2', text: '1. Mehendi — the long, fragrant beginning' },
      { type: 'p', text: 'A short paragraph on the meaning of mehendi (a wish for love, a promise of patience), a candid photo of palms being painted, and a soft sage-and-marigold palette make this event feel like the warm welcome it is. On the page, give it space — three or four lines, a single beautiful image, and the time + venue.' },
      { type: 'h2', text: '2. Haldi — sunlit, golden, ancient' },
      { type: 'p', text: 'Haldi loves yellow. Let the section background lean warm — a soft saffron, a hint of butter-gold — and write one honest sentence about why turmeric is brushed onto the soon-to-be-married. This is a moment that translates beautifully into video. A short reel set to gentle music is a gift to guests who could not attend.' },
      { type: 'h2', text: '3. Sangeet — the night the families sing' },
      { type: 'p', text: 'Sangeet is, at its heart, a love letter rehearsed in public. On the page, lean into joy: deeper colour, slightly bolder typography, a hint of motion. A short note explaining that family members will perform softens any nerves first-time guests may carry.' },
      { type: 'h2', text: '4. Baraat — the procession, the music, the welcome' },
      { type: 'p', text: 'A baraat is loud, splendid theatre — and easily misunderstood. A small explainer paragraph ("the groom\'s procession, accompanied by music and dance — guests are welcome to join the rhythm") changes everything for first-time attendees. Pair with a single photograph that captures the energy.' },
      { type: 'h2', text: '5. Ganesh Puja — the quiet, first prayer' },
      { type: 'p', text: 'Many Indian weddings open with a Ganesh puja — a request for obstacles to gently move. A two-line description, a small illustration of Ganesha (we hand-draw these for our studio clients), and the time of the puja is enough. The page does not need to over-explain; reverence is felt, not announced.' },
      { type: 'h2', text: '6. Saat Pheras — the seven sacred steps' },
      { type: 'p', text: 'For the actual ceremony, restraint matters most. List the seven vows in short, translated lines. Avoid stock photography here — use your own pre-wedding shoot or, better still, ask your photographer for a single still of the mandap. The page becomes a soft glossary for guests who will witness it for the first time.' },
      { type: 'h2', text: '7. Vidaai — the bittersweet farewell' },
      { type: 'p', text: 'If your wedding includes a vidaai, prepare guests gently in advance. A single, honest sentence ("a farewell as the bride leaves her parental home — expect tears, expect love") is the right amount. Save the cinematic photograph for the gallery, after the day.' },
      { type: 'h2', text: '8. Dress codes — by colour, never by judgement' },
      { type: 'p', text: 'Indian weddings have layered dress codes; tell guests gently. "Mehendi — soft pastels", "Sangeet — jewel tones", "Wedding — your most ceremonial best". Visual swatches help. Apologise (in tone) for nothing.' },
      { type: 'h2', text: '9. Regional dishes — name them, photograph them' },
      { type: 'p', text: 'A small "what we are eating" section, with each dish named in its mother tongue, is a quiet, profound act of cultural pride. Bisi bele bath, sannas, biryani, payasam — let the dishes have their full names on the page.' },
      { type: 'h2', text: '10. A glossary at the end' },
      { type: 'p', text: 'Three to five lines explaining the words you use most — mandap, jaimala, baraat, sangeet, vidaai. A tiny, kind gesture for the friend who has never been to an Indian wedding. They will remember it long after the day.' },
      { type: 'h2', text: 'Let tradition lead' },
      { type: 'p', text: 'The temptation, when building a wedding website, is to flatten your culture for clarity. The opposite move — being unapologetically specific, but quietly hospitable — is what makes a wedding feel like its own. Let the page lead with tradition; let design follow.' },
      { type: 'cta', text: 'Begin your Vivoha wedding website', href: '/#pricing' },
    ],
  },
  {
    slug: 'designing-invitations-that-feel-like-you',
    title: 'Designing Wedding Invitations That Feel Like You: A Modern Couple\'s Guide',
    eyebrow: 'On voice, tone and the quiet beauty of restraint',
    excerpt:
      'The most memorable invitations are not the loudest — they are the most honest. Here is the studio playbook for writing, designing and sending an invite that feels unmistakably yours.',
    cover: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1400&q=80',
    author: 'The Vivoha Studio',
    date: '2026-02-10',
    readTime: '7 min read',
    tags: ['Invitations', 'Design'],
    seoTitle: 'Designing Wedding Invitations That Feel Like You · Vivoha',
    seoDescription:
      'A studio playbook for crafting wedding invitations — typography, language, restraint and tone — that feel unmistakably yours, on paper and on screen.',
    body: [
      { type: 'p', text: 'There is a small, defining moment in every wedding plan — the moment the invitation arrives in someone\'s hands. It is the first time your guests touch your day. The card is heavier than they expected. The typeface is something they have not seen elsewhere. They read the names twice, smiling. It is, for a brief moment, the entire wedding distilled into a square of paper.' },
      { type: 'p', text: 'In our studio, we hold this moment sacred. Below is the same playbook we use with every couple — whether their invitation is a hand-pressed card, a digital scroll, or both.' },
      { type: 'h2', text: 'Begin with voice, not visual' },
      { type: 'p', text: 'It is tempting to start with colours and fonts. Resist it for an hour. Open a blank page and write a single paragraph in the way the two of you actually speak to your closest friend. Are you formal? Wry? Tender? Slightly mischievous? That paragraph becomes the voice of the invitation. Every visual decision that follows must serve it.' },
      { type: 'h2', text: 'One typeface for the heart, one for the head' },
      { type: 'p', text: 'A great invitation uses two fonts at most — usually a calligraphic or romantic serif for the couple\'s names (Great Vibes, Allura, Italiana), and a quieter sans-serif or book serif for everything else (Inter, Crimson Pro, Cormorant Garamond). The contrast is what gives the invitation its rhythm. Three or more fonts feel anxious; two feel composed.' },
      { type: 'h2', text: 'Names lead. Always.' },
      { type: 'p', text: 'The largest, most beautiful piece of typography on the invitation should be your names. Not the date. Not the venue. Not the families. The names. Everything else gathers around them like guests around a fire.' },
      { type: 'h2', text: 'Write less than you think you need' },
      { type: 'p', text: 'A short, well-chosen sentence is more memorable than a long, well-meaning paragraph. "Their families warmly invite you to celebrate as Anaya and Vihaan begin their forever, on the seventeenth of November." That is enough. Resist the urge to over-explain joy.' },
      { type: 'h2', text: 'On photography' },
      { type: 'p', text: 'If you include a photograph, choose one that is not posed. The candid moment — a glance, a laugh, a hand reaching across — does more for an invitation than a magazine portrait. If you do not have such a photo, no photo is better than the wrong one.' },
      { type: 'h2', text: 'Palette: two anchors, one accent' },
      { type: 'p', text: 'Most beloved invitations live on two anchor colours (usually a deep + a soft) and one accent (often gold, blush, or sage). Three colours, well chosen, will outclass eight colours every time. Trust restraint.' },
      { type: 'h2', text: 'The digital invitation deserves the same care' },
      { type: 'p', text: 'A wedding website is not a downgrade of the paper card — it is its second life. It should breathe the same voice, carry the same fonts, and feel like an extension of the envelope. Vivoha\'s 12 templates are built on this idea: paper-feeling, restraint-led, and unmistakably wedding-grade.' },
      { type: 'h2', text: 'The smallest details matter most' },
      { type: 'p', text: 'A wax seal. A folded corner. A single dried flower. A line of Sanskrit calligraphy under the names. These are the touches your guests will remember twenty years from now — far more than the gradient or the venue map.' },
      { type: 'p', text: 'A well-made invitation is a vow before the vow. It says, before anything else, "we took our time."' },
      { type: 'cta', text: 'Browse Vivoha templates', href: '/#templates' },
    ],
  },
  {
    slug: 'why-live-photo-walls-matter',
    title: 'Your Wedding Photo Wall: Why Live Memories Beat Static Galleries',
    eyebrow: 'Letting your guests photograph your day, in real time',
    excerpt:
      'A static gallery is yesterday\'s wedding. A live photo wall — moderated, beautiful, instant — is what couples will remember most. Here is how to make it sing.',
    cover: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=1400&q=80',
    author: 'The Vivoha Studio',
    date: '2026-02-05',
    readTime: '6 min read',
    tags: ['Photo Wall', 'Guests'],
    seoTitle: 'Why Live Photo Walls Matter at Indian Weddings · Vivoha',
    seoDescription:
      'A live photo wall lets guests upload memories in real time during your wedding — moderated, instant, beautiful. Vivoha studio explains how to do it right.',
    body: [
      { type: 'p', text: 'When a wedding ends, what stays behind are the moments your professional photographer could not be in. The aunt holding her sister\'s hand during the pheras. The cousin who slipped backstage between courses. The friend who caught the bride mid-laugh. These are the photographs you cannot ask for — they are gifted to you.' },
      { type: 'p', text: 'The live photo wall is how those gifts find their way to you, in real time, before anyone forgets to share them.' },
      { type: 'h2', text: 'What a photo wall is, exactly' },
      { type: 'p', text: 'A photo wall is a section of your wedding website that lets your guests upload their own photographs — from their phones, in real time, while the wedding is happening. Each photo flows into a moderation queue. You (or your studio) approve them in seconds. The approved photos appear, instantly, on a beautiful gallery that all your guests can see.' },
      { type: 'p', text: 'The result: a curated, living, ever-growing wall of your wedding — visible to family across the world, by the end of the same evening.' },
      { type: 'h2', text: 'Why static galleries fall short' },
      { type: 'p', text: 'A traditional gallery is built two to three weeks after the wedding, by which time the urgency is gone, the WhatsApp groups are quiet, and most of the candid photos sit unsent on a hundred phones. A photo wall closes that gap by inviting guests to share in the moment, when feelings are still high and the photos still feel important.' },
      { type: 'h2', text: 'Moderation is the secret' },
      { type: 'p', text: 'Without moderation, a photo wall becomes noise. With it, a photo wall becomes art. The Vivoha photo wall lets you (or our studio) approve every photo in a single tap. We screen for blurry shots, double-uploads, awkward angles — the gallery that emerges is curated, even if it is built by a hundred different cameras.' },
      { type: 'h2', text: 'How guests participate' },
      { type: 'p', text: 'Print a small QR code on your reception table cards (Vivoha generates one automatically). Guests scan, upload, and the photo appears in your moderation queue within seconds. No app downloads. No accounts. No friction.' },
      { type: 'h2', text: 'A note on privacy' },
      { type: 'p', text: 'The photo wall is private by default. Only invited guests with the link or QR code can upload. Only you and the studio can approve. The wall is hidden until the event begins, then automatically locks down again the morning after the wedding — so the page never becomes an open photo dump.' },
      { type: 'h2', text: 'What to do with the photos after' },
      { type: 'p', text: 'At the end of the wedding window, download the entire collection as a single ZIP archive (Vivoha offers a one-click download). Many couples build a small physical photo book from the wall — fifty photographs, curated by your guests, each one taken with affection. It is, without question, the most beloved keepsake of the wedding.' },
      { type: 'h2', text: 'Who should add a photo wall?' },
      { type: 'p', text: 'Any couple hosting more than fifty guests. Any couple who wants to remember the smaller moments. Any couple who wants their family abroad to feel a little less far away on the day. The photo wall, in our opinion, is the single most under-loved feature of modern weddings — and once a couple sees it in action, they cannot imagine the wedding without it.' },
      { type: 'cta', text: 'See the photo wall in action', href: '/wedding/preview-moonveil' },
    ],
  },
]

export function findPost(slug) {
  return BLOG_POSTS.find(p => p.slug === slug) || null
}
